use std::{
    ops::Deref,
    sync::{
        Arc, LazyLock,
        atomic::{AtomicBool, Ordering::Relaxed},
    },
};

use indexmap::IndexMap;

// Let's call this Flags.rs v1 (09-06-2026).

// TODO if you generate an enum here, you can pass it to Clap so we get autocompletion

macro_rules! define_flags {
    ( $( $name:ident = $init:expr ),* $(,)? ) => {

        $( pub const $name: &str = stringify!($name); )*

        paste::paste! {
            $( pub static [<$name _FLAG>]: LazyLock<Arc<Flag>> =
                LazyLock::new(|| Arc::new(Flag::new($init))); )*

            fn build_map() -> IndexMap<&'static str, Arc<Flag>> {
                IndexMap::from([
                    $( ($name, Arc::clone(&[<$name _FLAG>])), )*
                ])
            }
        }
    };
}

// TODO split up the flags into FLAGS_MISC and FLAGS_CONSOLE, then use inventory crate to merge them together
define_flags! {
   /* misc */ LOG_TO_GODOT = false, // If true, logs to Godot. Slower, but will cause them to appear in Godot's log files. (useful for debugging other people's PCs)
   /* console */ ADV_GODOT_EXPR_EVAL_PRINT_SRC_CODE = false, // If true, causes the advanced Godot expression evaluator to print the full source code for every ad-hoc script it generates. It's spammy, so disabled by default.
   /* misc */ TRACY_CREATE_FRAME_PER_ANIM = false, // If true, create a Tracy non-continuous frame for every line/flash animation (useful for debugging, but also prone to spam)
   /* console */ PLOT_USE_TEXTURE_CACHE = true, // If true, every plot stores its Vec<u8> and Gd<Texture2D> and re-uses it instead of creating new ones every time
}

pub struct Flag(AtomicBool);

impl Flag {
    const fn new(val: bool) -> Self {
        Self(AtomicBool::new(val))
    }

    pub fn get(&self) -> bool {
        self.0.load(Relaxed)
    }

    pub fn set(&self, val: bool) {
        self.0.store(val, Relaxed);
    }

    /// Returns the NEW value
    pub fn toggle(&self) -> bool {
        !self.0.fetch_not(Relaxed)
    }
}

// Actually we can't put FLAGS_CONSOLE in console, because then we have two separate Flags structs.
// So FLAGS_MISC.get("my_flag") won't find the flags in FLAGS_CONSOLE.
// maybe use `inventory` crate instead to gather them across all crates?
pub static FLAGS_MISC: LazyLock<Flags> = LazyLock::new(|| Flags::new(build_map())); // <-- build_map = generated by define_flags! macro

/// Global hashmap storing boolean flags.
///
/// This `HashMap` is useful if you want to toggle these flags at runtime from a console or something.
/// Now using `IndexMap` to keep the order we set at compile time.
/// Actually that won't work with `inventory` crate, it's effectively random. Maybe sort them then?
pub struct Flags(IndexMap<&'static str, Arc<Flag>>);

impl Deref for Flags {
    type Target = IndexMap<&'static str, Arc<Flag>>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl Flags {
    const fn new(m: IndexMap<&'static str, Arc<Flag>>) -> Self {
        Self(m)
    }

    pub fn get(&self, key: &str) -> Option<bool> {
        self.0.get(key).map(|f| f.get())
    }

    /// Sets a flag. Returns the new value if valid, else None
    pub fn set(&self, key: &str, value: bool) -> Option<bool> {
        match self.0.get(key) {
            Some(f) => {
                f.set(value);
                Some(value)
            }
            None => None,
        }
    }
    /// Toggle a flag. Returns the NEW value if valid, else None
    pub fn toggle(&self, key: &str) -> Option<bool> {
        self.0.get(key).map(|f| f.toggle())
    }
}
