name: Build and Test

on:
  push: # run on a push to any branch that does NOT have a tag (we run release.yml instead then)
    branches: ['**']
    tags-ignore: ['**']
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 # pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04  # pin OS version to avoid depending on too recent version of libc
    # defaults:
      # run: # set cwd for all steps to ./rust by default, but can be overridden
        # working-directory: ./rust
    steps:
      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a 

      - name: Install just
        run: pipx install "rust-just==1.58.0"

      - name: Install Nextest
        uses: taiki-e/install-action@fa23953489c080190314742a9b907f8e97c6767c
        with:
          tool: nextest@0.9.143

      # important: run this in the `rust` folder, otherwise it doesn't pick up the rust-toolchain.toml file
      - name: Add Windows (GNU) rust target and install MinGW toolchain
        working-directory: ./rust
        run: |
          rustup target add x86_64-pc-windows-gnu
          sudo apt-get update && sudo apt-get install -y mingw-w64

      - name: Build (Linux)
        timeout-minutes: 5 # prevent wasting CI time if it stalls - typically takes 3min
        run: just build-release

      - name: Build (Windows)
        timeout-minutes: 5 # prevent wasting CI time if it stalls - typically takes 3min
        run: just build-release --target x86_64-pc-windows-gnu

      - name: Strip .so to reduce size
        working-directory: ./rust/target/release
        run: strip *.so

      - name: Strip .dll to reduce size
        working-directory: ./rust/target/x86_64-pc-windows-gnu/release/
        run: strip *.dll

      - name: Copy libraries to addons folder
        run: |
          just copy-so-release
          just copy-dll-release

      - name: Install Godot v4.6.2
        working-directory: /usr/local/bin/
        run: |
          wget -O godot.zip "https://downloads.godotengine.org/?version=4.6.2&flavor=stable&slug=linux.x86_64.zip&platform=linux.64"
          unzip godot.zip
          rm godot.zip
          mv Godot_v4.6.2-stable_linux.x86_64 godot
          # may not be needed, since /usr/local/bin is in PATH already
          # echo "GODOT4_BIN=$(realpath Godot_v4.6.2-stable_linux.x86_64)" >> "$GITHUB_ENV"

      - name: Run tests (release)
        run: just test-release

      - name: Upload addons folder
        # working-directory: .
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a
        with:
          name: crabbyconsole
          # hack: include a dummy file to preserve `addons` folder in .zip.
          # see https://github.com/actions/upload-artifact/issues/174
          # .gitignore does not actually end up in the zip file, it seems it gets removed automatically.
          path: |
            godot/addons
            godot/.gitignore 
          if-no-files-found: error