# This is a basic workflow to help you get started with Actions

name: Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # deploy step
  deploy:

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

        # see https://zensical.org/docs/publish-your-site/

      - uses: actions/checkout@f548e57e544e1ff5a4c46bf1e1b8685f8e4a348a

      - uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      # - uses: actions/setup-python@v6
      #   with:
      #     python-version: 3.x

      - name: Install uv and just
        run: pipx install "uv==0.12.9" && pipx install "rust-just==1.58.0"

      - name: Uv sync
        working-directory: docs/
        run: uv sync --locked

      - name: Generate CLI docs
        run: just generate-cli-docs-debug

      - name: Build site
        working-directory: docs/
        run: uv run zensical build --clean --strict

      - uses: actions/upload-pages-artifact@98ef48e41587a300b82de4cf298aa98b57b2faae
        with:
          path: docs/site
          retention-days: 1 # no need to keep these around, the site remains alive anyway

      - uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346
        id: deployment
